name: Build develop on push

on:
  push:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build for linux
      run: mkdir linux && GOOS=linux GOARCH=amd64 go build -v -o linux/sslr .

    - name: Build for macos
      run: mkdir macos && GOOS=darwin GOARCH=amd64 go build -v -o macos/sslr .
      
    - name: Build for windows
      run: mkdir windows && GOOS=windows GOARCH=amd64 go build -v -o windows/sslr.exe .
